Feature/add comment
NSS-Day-Cohort-68/rare-client-rare-team-4 pull request #60
Opened 2024-03-13 18:51 UTC by KSummers16

adding a component with a form to add comments to a post

This feature will allow a customer to write a comment when they are looking at a detailed page of a particular post. 

NewComment.py component that is displayed in the PostDetails.py component. It shows an input field, and anything that the user writes in the input field will be saved, as well as the user's id and the id of the post. 

To test: (make sure that your database is running). Click on a particular post, then there will be a "New Comment" section. Put a comment in the input field and then click submit. Once you are shown a new empty input field then you can check postman to see if your comment was added (the ability to see comments on the page will come with a later ticket)

2024-03-13 19:25 UTC, HewsonSchulz requested changes
The functionality is there, and when I submit a comment, it does post it to the database correctly. However, there are a couple things that should be changed.
- The ticket states that "the creation `datetime` should be automatically set to the current date and time". Although this is not included in the ERD, Steve has told us that the ticket info takes the highest priority, and that the ERD/Wireframe are outdated. This means that each comment should have a `date_created` or something similar. This can be fully implemented on the backend, and has already been done before with the `users` creation (_see `user.py`, `create_user`_).
- The ticket also states that "the user should be redirected to the new Comments list page for the related Post". It's totally fine that this functionality is going to be implemented in a future PR. But if that's the case, then you should unlink the ticket from the development tab, because otherwise, it will automatically mark the ticket as closed when this PR is merged.
- Lastly, the styling is broken for posts that contain a header image (_see attached screenshots_).

<img width="1305" alt="Screen Shot 1" src="https://github.com/NSS-Day-Cohort-68/rare-client-rare-team-4/assets/147445675/4ac0026d-1626-49d8-91cd-98f94dab434c">
<img width="1301" alt="Screen Shot 2" src="https://github.com/NSS-Day-Cohort-68/rare-client-rare-team-4/assets/147445675/afd61501-8916-4ca9-b46f-8cb4cbdef7a7">

2024-03-13 20:42 UTC, KSummers16 commented
So the header images aren't part of my component. Those were there from the "PostDetails" component. But I will fix the rest for sure

2024-03-14 14:52 UTC, HewsonSchulz commented
> So the header images aren't part of my component. Those were there from the "PostDetails" component. But I will fix the rest for sure

I understand that this was not part of your ticket, but your branch currently has broken this styling. This will need to be fixed back how it was before merging. This is what it currently looks like in the `main` branch:

<img width="847" alt="Screen Shot 2024-03-14 at 09 42 46" src="https://github.com/NSS-Day-Cohort-68/rare-client-rare-team-4/assets/147445675/fbf92d6f-0d5d-4881-bbbb-5fdd9866375c">

2024-03-14 19:07 UTC, HewsonSchulz requested changes
The functionality is all there and seems to work correctly. However, there may have been a mistaken backwards merge when resolving merge conflicts.

2024-03-14 19:07 UTC, HewsonSchulz commented on src/components/views/ApplicationViews.js
> +      /> */}
This should not be commented out, as it allows users to access pages that do not exist.

2024-03-14 19:07 UTC, HewsonSchulz commented on src/components/views/ApplicationViews.js
> +        <Route path="/tags/create" element={<CreateTagForm />} />
I noticed that I cannot currently access the **Category Manager** view, or the **Category Creation** view. Upon further inspection, it looks like you may have accepted the wrong result when dealing with merge conflicts in `ApplicationViews.js`. The current implementation of `main` includes nested routes for `/categories` and `/tags` in order to support the `/tags/create` and `/categories/create` views. But in your branch, this is what I see when looking at the file changes:

<img width="931" alt="Screen Shot" src="https://github.com/NSS-Day-Cohort-68/rare-client-rare-team-4/assets/147445675/6428ca41-a145-41dd-8caa-b41b601ddfc2">

Lines 42-49 (red) should replace lines 49-52 (green) in order to fix this, and revert this change.

2024-03-14 20:43 UTC, HewsonSchulz requested changes
The functionality is all there and seems to work correctly. However, when attempting to access the **Tag Creation** page, I am redirected to the home page.

2024-03-14 20:43 UTC, HewsonSchulz commented on src/components/views/ApplicationViews.js
> -          <Route path="create" element={<CreateTagForm />} />
This line is still needed.

2024-03-15 15:01 UTC, HewsonSchulz requested changes
![Screen Shot](https://github.com/NSS-Day-Cohort-68/rare-client-rare-team-4/assets/147445675/098185ce-d34e-4f4e-b3b9-0d7165ac49d9)

2024-03-15 15:07 UTC, KSummers16 commented on src/components/views/posts/PostDetails.js
> +            </h3>
Fixed that now

2024-03-15 15:11 UTC, HewsonSchulz approved these changes
All works as intended.

2024-03-15 15:11 UTC, merged